# Generated by Django 4.2.7 on 2026-06-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_points_profile_points_redeemed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rupees_per_point_earned', models.IntegerField(default=25, help_text='Amount in ₹ to spend to earn 1 point')),
                ('redemption_rate_per_point', models.DecimalField(decimal_places=2, default=0.1, help_text='Value of 1 point in ₹ (e.g., 0.10 means 100 points = ₹10)', max_digits=5)),
                ('minimum_points_to_redeem', models.IntegerField(default=100, help_text='Minimum points required to redeem')),
                ('bonus_points_percentage', models.IntegerField(default=0, help_text='Extra bonus percentage (e.g., 10 for 10% more points)')),
            ],
            options={
                'verbose_name': 'Loyalty Setting',
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
    ]
