# Generated by Django 4.2.7 on 2026-06-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loyaltysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_amount', models.PositiveIntegerField(default=1, help_text='Amount spent in ₹ to earn points')),
                ('points_per_spend', models.PositiveIntegerField(default=1, help_text='Points earned per spend amount')),
                ('points_to_rupee', models.PositiveIntegerField(default=100, help_text='Points needed for ₹10 discount')),
                ('rupee_per_redeem', models.PositiveIntegerField(default=10, help_text='₹ discount per points_to_rupee points')),
                ('min_redeem_points', models.PositiveIntegerField(default=500, help_text='Minimum points to redeem')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable loyalty system')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Settings',
            },
        ),
        migrations.DeleteModel(
            name='LoyaltySetting',
        ),
    ]
